# Generated by Django 3.2.3 on 2021-06-01 19:57

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
            preserve_default=False,
        ),
    ]
