# Generated by Django 3.2.3 on 2021-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.TextField()),
                ('meal_type', models.PositiveSmallIntegerField(choices=[(1, 'Default'), (2, 'Vegetarian'), (3, 'Vegan')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_period', models.PositiveSmallIntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner')], default=1)),
                ('meals', models.ManyToManyField(to='restaurant.Meal')),
            ],
            options={
                'unique_together': {('date', 'day_period')},
            },
        ),
    ]
