# Generated by Django 3.2.3 on 2021-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210602_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchase_code',
            field=models.CharField(max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
